### PR TITLE
release v1.5.2

### PR DESCRIPTION
**Pull request by ghost**
also GNOME 43.

### CODE REVIEW

**Comment by ghost** [comment]
```json
    "errors": [
        "flathub-json-modified-publish-delay"
    ]
```
are we not allowed to do that anymore? :thinking:

**Comment by ghost** [comment]
So I didn't change the installation method or anything, everything was working fine up until now, and it still works in the AUR.

But now my Python module fails to properly install here.
```
ModuleNotFoundError: No module named 'myuzi'
```
And all I did here was switch to GNOME 43 and bump the version tag :confused:

**Comment by hfiguiere** [comment]
> ```json
>     "errors": [
>         "flathub-json-modified-publish-delay"
>     ]
> ```
> 
> are we not allowed to do that anymore? thinking

You never were, just that it wasn't enforced.

**Comment by hfiguiere** [comment]
GNMOE 43 use Python 3.10. This could be the breakage.

**Comment by hfiguiere** [comment]
build fail because the screenshot isn't found (404). That's what happen when you link to the tip of a branch and not a specific tag/commit.

**Comment by ghost** [comment]
```
    Gio.ApplicationFlags.DEFAULT_FLAGS
AttributeError: type object 'ApplicationFlags' has no attribute 'DEFAULT_FLAGS'
```
I guess the 42 runtime uses [GIO<2.74](https://docs.gtk.org/gio/flags.ApplicationFlags.html#default_flags).

**Comment by ghost** [comment]
```
AttributeError: 'gi.repository.Adw' object has no attribute 'AboutWindow'
```
And Libadwaita<1.2 :disappointed:

Looks like the only thing I can do is try to get 43 to work.

**Comment by ghost** [comment]
There's no errors in the build, but still, "no module named myuzi".

**Pull request merged**
